CREATE SCHEMA `blogdb` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE `blogdb`.`POSTS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TITLE` VARCHAR(255) NOT NULL,
  `POST_TEXT` VARCHAR(45) NOT NULL,
  `POST_TIME` TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`ID`));